"use client";

import { useState } from "react";
import { Sparkles, FileText, Rocket, ClipboardList, BookOpen, PieChart, Briefcase } from "lucide-react";
import { Card } from "@/components/ui";

const GENERATORS = [
  { icon: Rocket, title: "Release Notes", desc: "From merged PRs and closed issues", time: "~15s" },
  { icon: BookOpen, title: "Technical Documentation", desc: "From code changes and ADRs", time: "~40s" },
  { icon: ClipboardList, title: "User Stories", desc: "From a feature description", time: "~10s" },
  { icon: PieChart, title: "Sprint Report", desc: "Velocity, scope changes, carry-over", time: "~15s" },
  { icon: FileText, title: "Project Report", desc: "Status, risks, forecast, next steps", time: "~20s" },
  { icon: Briefcase, title: "Executive Summary", desc: "CEO-friendly, one page", time: "~10s" },
];

const RECENT = [
  { title: "Release Notes — Banking v2.4.0", when: "Today, 09:12", by: "AI · reviewed by Aarav" },
  { title: "Sprint 13 Retrospective Summary", when: "Yesterday", by: "AI · auto-generated" },
  { title: "Q3 Portfolio Executive Summary", when: "Jul 07", by: "AI · exported to PDF" },
  { title: "Data Migration Runbook", when: "Jul 04", by: "Rohan + AI edits" },
];

export default function DocsHub() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [done, setDone] = useState<string[]>([]);

  const generate = (title: string) => {
    setGenerating(title);
    setTimeout(() => {
      setGenerating(null);
      setDone((d) => [...d, title]);
    }, 1600);
  };

  return (
    <div className="mx-auto max-w-7xl space-y-5">
      <div className="float-up">
        <h1 className="text-2xl font-bold tracking-tight">Docs Hub</h1>
        <p className="mt-1 text-sm text-ink-2">One click → professional documentation, written from live project data</p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {GENERATORS.map(({ icon: Icon, title, desc, time }, i) => (
          <Card key={title} className="float-up" >
            <div className="flex items-start justify-between">
              <span className="flex h-10 w-10 items-center justify-center rounded-xl" style={{ background: "var(--brand-soft)", color: "var(--brand)" }}>
                <Icon size={17} />
              </span>
              <span className="text-[11px] text-ink-3">{time}</span>
            </div>
            <h3 className="mt-3 font-semibold">{title}</h3>
            <p className="mt-1 text-[13px] text-ink-2">{desc}</p>
            <button
              onClick={() => generate(title)}
              disabled={generating === title}
              className="btn-primary mt-4 w-full px-3 py-2 text-xs disabled:opacity-70">
              {generating === title ? (
                <span className="pulse-dot">Generating…</span>
              ) : done.includes(title) ? (
                "✓ Generated — open"
              ) : (
                <><Sparkles size={12} /> Generate</>
              )}
            </button>
          </Card>
        ))}
      </div>

      <Card title="Recent documents">
        <ul className="divide-y divide-line">
          {[...done.map((t) => ({ title: t, when: "Just now", by: "AI · generated by you" })), ...RECENT].map((d, i) => (
            <li key={d.title + i} className="flex flex-wrap items-center gap-3 py-3">
              <FileText size={15} className="text-ink-3" />
              <span className="min-w-0 flex-1 truncate text-sm font-medium">{d.title}</span>
              <span className="text-xs text-ink-3">{d.by}</span>
              <span className="w-24 text-right text-xs text-ink-3">{d.when}</span>
            </li>
          ))}
        </ul>
      </Card>
    </div>
  );
}
